on:
  push:
    paths: ['explore/input_lists.json']
    branches: ['master']

jobs:
  update-catalog:
    runs-on: ubuntu-20.04
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: set up python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'
      - name: install
        run: |
          python -m pip install --upgrade pip
          pip install pytz
      - name: update
        run: |
          cd explore/scripts/
          GITHUB_API_TOKEN="${{ secrets.GITHUB_TOKEN }}" ./MASTER.sh

      - name: commit new data
        run: |
          git config user.name "GitHub Actions Bot"
          git config user.email "<>"
          git add -u explore/github-data/
          git commit -m "Update catalog commit"
          git push origin master
