on:
  push:
    paths: ['projects.md']
    branches: ['master']
            
jobs:
  update-projectstoc:
    runs-on: ubuntu-20.04
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: gh-md-toc
        run: |
          wget https://raw.githubusercontent.com/ekalinin/github-markdown-toc/master/gh-md-toc
          chmod a+x gh-md-toc
      - name: generate-toc
        run: |
          ./gh-md-toc --insert --no-backup projects.md
          rm gh-md-toc
      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Auto update markdown TOC
